# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, DependsOnSequence, Graph, Node
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_max as dataframe_column_max,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_mean as dataframe_column_mean,
)
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import map_values as map_values
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_core.tasks.transformation import with_unit as with_unit
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density as calculate_elliptical_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    get_night_day_ratio as get_night_day_ratio,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polygon_layer as create_polygon_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecoplot as draw_ecoplot
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    classify_is_night as classify_is_night,
)
from ecoscope_workflows_ext_ecoscope.tasks.warning import (
    mixed_subtype_warning as mixed_subtype_warning,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client_name": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "subject_obs": ["er_client_name", "time_range"],
        "warn_if_mixed_subtype": ["subject_obs"],
        "convert_to_user_timezone": ["subject_obs", "get_timezone"],
        "groupers": [],
        "subject_reloc": ["convert_to_user_timezone"],
        "day_night_labels": ["subject_reloc"],
        "subject_traj": ["day_night_labels"],
        "traj_add_temporal_index": ["subject_traj", "groupers"],
        "rename_grouper_columns": ["traj_add_temporal_index"],
        "map_subject_sex": ["rename_grouper_columns"],
        "classify_traj_speed": ["map_subject_sex"],
        "set_traj_map_title": [],
        "set_td_map_title": [],
        "set_night_day_map_title": [],
        "set_nsd_chart_title": [],
        "split_subject_traj_groups": ["classify_traj_speed", "groupers"],
        "base_map_defs": [],
        "sort_traj_speed": ["split_subject_traj_groups"],
        "colormap_traj_speed": ["sort_traj_speed"],
        "rename_speed_display_columns": ["colormap_traj_speed"],
        "traj_map_layers": ["rename_speed_display_columns"],
        "traj_ecomap": ["base_map_defs", "set_traj_map_title", "traj_map_layers"],
        "ecomap_html_urls": ["traj_ecomap"],
        "traj_map_widgets_single_views": ["set_traj_map_title", "ecomap_html_urls"],
        "traj_grouped_map_widget": ["traj_map_widgets_single_views"],
        "sort_traj_night_day": ["split_subject_traj_groups"],
        "colormap_traj_night": ["sort_traj_night_day"],
        "rename_nightday_display_columns": ["colormap_traj_night"],
        "traj_map_night_layers": ["rename_nightday_display_columns"],
        "traj_nightday_ecomap": [
            "base_map_defs",
            "set_night_day_map_title",
            "traj_map_night_layers",
        ],
        "ecomap_nightday_html_urls": ["traj_nightday_ecomap"],
        "traj_map_nightday_widgets_sv": [
            "set_night_day_map_title",
            "ecomap_nightday_html_urls",
        ],
        "traj_nightday_grouped_map_widget": ["traj_map_nightday_widgets_sv"],
        "mean_speed": ["split_subject_traj_groups"],
        "average_speed_converted": ["mean_speed"],
        "mean_speed_sv_widgets": ["average_speed_converted"],
        "mean_speed_grouped_sv_widget": ["mean_speed_sv_widgets"],
        "max_speed": ["split_subject_traj_groups"],
        "max_speed_converted": ["max_speed"],
        "max_speed_sv_widgets": ["max_speed_converted"],
        "max_speed_grouped_sv_widget": ["max_speed_sv_widgets"],
        "num_location": ["split_subject_traj_groups"],
        "num_location_sv_widgets": ["num_location"],
        "num_location_grouped_sv_widget": ["num_location_sv_widgets"],
        "nightday_ratio": ["split_subject_traj_groups"],
        "nightday_ratio_sv_widgets": ["nightday_ratio"],
        "nightday_ratio_grouped_sv_widget": ["nightday_ratio_sv_widgets"],
        "total_distance": ["split_subject_traj_groups"],
        "total_dist_converted": ["total_distance"],
        "total_distance_sv_widgets": ["total_dist_converted"],
        "total_dist_grouped_sv_widget": ["total_distance_sv_widgets"],
        "total_time": ["split_subject_traj_groups"],
        "total_time_converted": ["total_time"],
        "total_time_sv_widgets": ["total_time_converted"],
        "total_time_grouped_sv_widget": ["total_time_sv_widgets"],
        "td": ["split_subject_traj_groups"],
        "percentile_col_to_string": ["td"],
        "td_colormap": ["percentile_col_to_string"],
        "td_map_layer": ["td_colormap"],
        "td_ecomap": ["base_map_defs", "set_td_map_title", "td_map_layer"],
        "td_ecomap_html_url": ["td_ecomap"],
        "td_map_widget": ["set_td_map_title", "td_ecomap_html_url"],
        "td_grouped_map_widget": ["td_map_widget"],
        "nsd_rename_display_columns": ["split_subject_traj_groups"],
        "nsd_chart": ["set_nsd_chart_title", "nsd_rename_display_columns"],
        "nsd_chart_html_url": ["nsd_chart"],
        "nsd_chart_widget": ["set_nsd_chart_title", "nsd_chart_html_url"],
        "grouped_nsd_chart_widget_merge": ["nsd_chart_widget"],
        "subject_tracking_dashboard": [
            "workflow_details",
            "traj_grouped_map_widget",
            "mean_speed_grouped_sv_widget",
            "max_speed_grouped_sv_widget",
            "num_location_grouped_sv_widget",
            "nightday_ratio_grouped_sv_widget",
            "total_dist_grouped_sv_widget",
            "total_time_grouped_sv_widget",
            "td_grouped_map_widget",
            "traj_nightday_grouped_map_widget",
            "grouped_nsd_chart_widget_merge",
            "groupers",
            "time_range",
            "warn_if_mixed_subtype",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "subject_obs": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("subject_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
            }
            | (params_dict.get("subject_obs") or {}),
            method="call",
        ),
        "warn_if_mixed_subtype": Node(
            async_task=mixed_subtype_warning.validate()
            .set_task_instance_id("warn_if_mixed_subtype")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "subject_obs": DependsOn("subject_obs"),
            }
            | (params_dict.get("warn_if_mixed_subtype") or {}),
            method="call",
        ),
        "convert_to_user_timezone": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_to_user_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_obs"),
                "timezone": DependsOn("get_timezone"),
                "columns": ["fixtime"],
            }
            | (params_dict.get("convert_to_user_timezone") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "subject_reloc": Node(
            async_task=process_relocations.validate()
            .set_task_instance_id("subject_reloc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("convert_to_user_timezone"),
                "relocs_columns": [
                    "groupby_col",
                    "fixtime",
                    "junk_status",
                    "geometry",
                    "extra__subject__name",
                    "extra__subject__subject_subtype",
                    "extra__subject__sex",
                ],
                "filter_point_coords": [
                    {"x": 180.0, "y": 90.0},
                    {"x": 0.0, "y": 0.0},
                    {"x": 1.0, "y": 1.0},
                ],
            }
            | (params_dict.get("subject_reloc") or {}),
            method="call",
        ),
        "day_night_labels": Node(
            async_task=classify_is_night.validate()
            .set_task_instance_id("day_night_labels")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("subject_reloc"),
            }
            | (params_dict.get("day_night_labels") or {}),
            method="call",
        ),
        "subject_traj": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("subject_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("day_night_labels"),
            }
            | (params_dict.get("subject_traj") or {}),
            method="call",
        ),
        "traj_add_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("traj_add_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_traj"),
                "time_col": "segment_start",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("traj_add_temporal_index") or {}),
            method="call",
        ),
        "rename_grouper_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_grouper_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("traj_add_temporal_index"),
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "extra__name": "subject_name",
                    "extra__subject_subtype": "subject_subtype",
                    "extra__sex": "subject_sex",
                },
            }
            | (params_dict.get("rename_grouper_columns") or {}),
            method="call",
        ),
        "map_subject_sex": Node(
            async_task=map_values.validate()
            .set_task_instance_id("map_subject_sex")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_grouper_columns"),
                "column_name": "subject_sex",
                "value_map": {"male": "male", "female": "female"},
                "missing_values": "replace",
                "replacement": "unknown",
            }
            | (params_dict.get("map_subject_sex") or {}),
            method="call",
        ),
        "classify_traj_speed": Node(
            async_task=apply_classification.validate()
            .set_task_instance_id("classify_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_subject_sex"),
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_bins",
                "classification_options": {"scheme": "equal_interval", "k": 6},
                "label_options": {
                    "label_ranges": True,
                    "label_decimals": 1,
                    "label_suffix": " km/h",
                },
            }
            | (params_dict.get("classify_traj_speed") or {}),
            method="call",
        ),
        "set_traj_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_traj_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Subject Group Trajectory Map",
            }
            | (params_dict.get("set_traj_map_title") or {}),
            method="call",
        ),
        "set_td_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_td_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Home Range Map",
            }
            | (params_dict.get("set_td_map_title") or {}),
            method="call",
        ),
        "set_night_day_map_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_night_day_map_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Subject Group Night/Day Map",
            }
            | (params_dict.get("set_night_day_map_title") or {}),
            method="call",
        ),
        "set_nsd_chart_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_nsd_chart_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Net Square Displacement",
            }
            | (params_dict.get("set_nsd_chart_title") or {}),
            method="call",
        ),
        "split_subject_traj_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_subject_traj_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("classify_traj_speed"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_subject_traj_groups") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "sort_traj_speed": Node(
            async_task=sort_values.validate()
            .set_task_instance_id("sort_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "speed_kmhr",
                "ascending": True,
                "na_position": "last",
            }
            | (params_dict.get("sort_traj_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "colormap_traj_speed": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("colormap_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_colormap",
                "colormap": [
                    "#1a9850",
                    "#91cf60",
                    "#d9ef8b",
                    "#fee08b",
                    "#fc8d59",
                    "#d73027",
                ],
            }
            | (params_dict.get("colormap_traj_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_traj_speed"),
            },
        ),
        "rename_speed_display_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_speed_display_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "segment_start": "Start",
                    "timespan_seconds": "Duration (s)",
                    "speed_kmhr": "Speed (kph)",
                    "extra__is_night": "Nighttime",
                    "subject_name": "Subject Name",
                    "subject_sex": "Subject Sex",
                },
            }
            | (params_dict.get("rename_speed_display_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("colormap_traj_speed"),
            },
        ),
        "traj_map_layers": Node(
            async_task=create_polyline_layer.validate()
            .set_task_instance_id("traj_map_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "speed_bins_colormap"},
                "legend": {
                    "label_column": "speed_bins",
                    "color_column": "speed_bins_colormap",
                },
                "tooltip_columns": [
                    "Start",
                    "Duration (s)",
                    "Speed (kph)",
                    "Nighttime",
                    "Subject Name",
                    "Subject Sex",
                ],
            }
            | (params_dict.get("traj_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("rename_speed_display_columns"),
            },
        ),
        "traj_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("traj_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {
                    "title": "Speed",
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
                "widget_id": DependsOn("set_traj_map_title"),
            }
            | (params_dict.get("traj_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("traj_map_layers"),
            },
        ),
        "ecomap_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ecomap_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("ecomap_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("traj_ecomap"),
            },
        ),
        "traj_map_widgets_single_views": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("traj_map_widgets_single_views")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_traj_map_title"),
            }
            | (params_dict.get("traj_map_widgets_single_views") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("ecomap_html_urls"),
            },
        ),
        "traj_grouped_map_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("traj_grouped_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("traj_map_widgets_single_views"),
            }
            | (params_dict.get("traj_grouped_map_widget") or {}),
            method="call",
        ),
        "sort_traj_night_day": Node(
            async_task=sort_values.validate()
            .set_task_instance_id("sort_traj_night_day")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "extra__is_night",
                "ascending": False,
                "na_position": "last",
            }
            | (params_dict.get("sort_traj_night_day") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "colormap_traj_night": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("colormap_traj_night")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "colormap": ["#292965", "#e7a553"],
                "input_column_name": "extra__is_night",
                "output_column_name": "is_night_colors",
            }
            | (params_dict.get("colormap_traj_night") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_traj_night_day"),
            },
        ),
        "rename_nightday_display_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_nightday_display_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "subject_name": "Subject Name",
                    "subject_sex": "Subject Sex",
                    "extra__is_night": "Nighttime",
                },
            }
            | (params_dict.get("rename_nightday_display_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("colormap_traj_night"),
            },
        ),
        "traj_map_night_layers": Node(
            async_task=create_polyline_layer.validate()
            .set_task_instance_id("traj_map_night_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "is_night_colors"},
                "legend": {
                    "labels": ["Night", "Day"],
                    "colors": ["#292965", "#e7a553"],
                },
                "tooltip_columns": ["Subject Name", "Subject Sex", "Nighttime"],
            }
            | (params_dict.get("traj_map_night_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("rename_nightday_display_columns"),
            },
        ),
        "traj_nightday_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("traj_nightday_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {
                    "title": "Day / Night Movement",
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
                "widget_id": DependsOn("set_night_day_map_title"),
            }
            | (params_dict.get("traj_nightday_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("traj_map_night_layers"),
            },
        ),
        "ecomap_nightday_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ecomap_nightday_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("ecomap_nightday_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("traj_nightday_ecomap"),
            },
        ),
        "traj_map_nightday_widgets_sv": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("traj_map_nightday_widgets_sv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_night_day_map_title"),
            }
            | (params_dict.get("traj_map_nightday_widgets_sv") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("ecomap_nightday_html_urls"),
            },
        ),
        "traj_nightday_grouped_map_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("traj_nightday_grouped_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("traj_map_nightday_widgets_sv"),
            }
            | (params_dict.get("traj_nightday_grouped_map_widget") or {}),
            method="call",
        ),
        "mean_speed": Node(
            async_task=dataframe_column_mean.validate()
            .set_task_instance_id("mean_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "speed_kmhr",
            }
            | (params_dict.get("mean_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "average_speed_converted": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("average_speed_converted")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "km/h",
                "new_unit": "km/h",
            }
            | (params_dict.get("average_speed_converted") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value"],
                "argvalues": DependsOn("mean_speed"),
            },
        ),
        "mean_speed_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("mean_speed_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Mean Speed",
                "decimal_places": 1,
            }
            | (params_dict.get("mean_speed_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("average_speed_converted"),
            },
        ),
        "mean_speed_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("mean_speed_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("mean_speed_sv_widgets"),
            }
            | (params_dict.get("mean_speed_grouped_sv_widget") or {}),
            method="call",
        ),
        "max_speed": Node(
            async_task=dataframe_column_max.validate()
            .set_task_instance_id("max_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "speed_kmhr",
            }
            | (params_dict.get("max_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "max_speed_converted": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("max_speed_converted")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "km/h",
                "new_unit": "km/h",
            }
            | (params_dict.get("max_speed_converted") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value"],
                "argvalues": DependsOn("max_speed"),
            },
        ),
        "max_speed_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("max_speed_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Max Speed",
                "decimal_places": 1,
            }
            | (params_dict.get("max_speed_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("max_speed_converted"),
            },
        ),
        "max_speed_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("max_speed_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("max_speed_sv_widgets"),
            }
            | (params_dict.get("max_speed_grouped_sv_widget") or {}),
            method="call",
        ),
        "num_location": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("num_location")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("num_location") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "num_location_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("num_location_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Number of Locations",
                "decimal_places": 1,
            }
            | (params_dict.get("num_location_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("num_location"),
            },
        ),
        "num_location_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("num_location_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("num_location_sv_widgets"),
            }
            | (params_dict.get("num_location_grouped_sv_widget") or {}),
            method="call",
        ),
        "nightday_ratio": Node(
            async_task=get_night_day_ratio.validate()
            .set_task_instance_id("nightday_ratio")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("nightday_ratio") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "nightday_ratio_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("nightday_ratio_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Night/Day Ratio",
                "decimal_places": 1,
            }
            | (params_dict.get("nightday_ratio_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("nightday_ratio"),
            },
        ),
        "nightday_ratio_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("nightday_ratio_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("nightday_ratio_sv_widgets"),
            }
            | (params_dict.get("nightday_ratio_grouped_sv_widget") or {}),
            method="call",
        ),
        "total_distance": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_distance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "dist_meters",
            }
            | (params_dict.get("total_distance") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "total_dist_converted": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("total_dist_converted")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "m",
                "new_unit": "km",
            }
            | (params_dict.get("total_dist_converted") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value"],
                "argvalues": DependsOn("total_distance"),
            },
        ),
        "total_distance_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_distance_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Distance",
                "decimal_places": 1,
            }
            | (params_dict.get("total_distance_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("total_dist_converted"),
            },
        ),
        "total_dist_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("total_dist_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("total_distance_sv_widgets"),
            }
            | (params_dict.get("total_dist_grouped_sv_widget") or {}),
            method="call",
        ),
        "total_time": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_time")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "timespan_seconds",
            }
            | (params_dict.get("total_time") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "total_time_converted": Node(
            async_task=with_unit.validate()
            .set_task_instance_id("total_time_converted")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "original_unit": "s",
                "new_unit": "h",
            }
            | (params_dict.get("total_time_converted") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["value"],
                "argvalues": DependsOn("total_time"),
            },
        ),
        "total_time_sv_widgets": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_time_sv_widgets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Time",
                "decimal_places": 1,
            }
            | (params_dict.get("total_time_sv_widgets") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("total_time_converted"),
            },
        ),
        "total_time_grouped_sv_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("total_time_grouped_sv_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("total_time_sv_widgets"),
            }
            | (params_dict.get("total_time_grouped_sv_widget") or {}),
            method="call",
        ),
        "td": Node(
            async_task=calculate_elliptical_time_density.validate()
            .set_task_instance_id("td")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "percentiles": [50.0, 60.0, 70.0, 80.0, 90.0, 99.999],
                "nodata_value": "nan",
                "band_count": 1,
            }
            | (params_dict.get("td") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["trajectory_gdf"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "percentile_col_to_string": Node(
            async_task=convert_column_values_to_string.validate()
            .set_task_instance_id("percentile_col_to_string")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": ["percentile"],
            }
            | (params_dict.get("percentile_col_to_string") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("td"),
            },
        ),
        "td_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("td_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "percentile",
                "colormap": "RdYlGn_r",
                "output_column_name": "percentile_colormap",
            }
            | (params_dict.get("td_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("percentile_col_to_string"),
            },
        ),
        "td_map_layer": Node(
            async_task=create_polygon_layer.validate()
            .set_task_instance_id("td_map_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "percentile_colormap",
                    "opacity": 0.7,
                    "get_line_width": 0,
                },
                "legend": {
                    "label_column": "percentile",
                    "label_suffix": " %",
                    "color_column": "percentile_colormap",
                    "sort": "ascending",
                },
                "tooltip_columns": ["percentile"],
            }
            | (params_dict.get("td_map_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("td_colormap"),
            },
        ),
        "td_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("td_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {
                    "title": "Time Spent",
                    "format_title": False,
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
                "widget_id": DependsOn("set_td_map_title"),
            }
            | (params_dict.get("td_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("td_map_layer"),
            },
        ),
        "td_ecomap_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("td_ecomap_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("td_ecomap_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("td_ecomap"),
            },
        ),
        "td_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("td_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_td_map_title"),
            }
            | (params_dict.get("td_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("td_ecomap_html_url"),
            },
        ),
        "td_grouped_map_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("td_grouped_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("td_map_widget"),
            }
            | (params_dict.get("td_grouped_map_widget") or {}),
            method="call",
        ),
        "nsd_rename_display_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("nsd_rename_display_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {"segment_start": "Time", "nsd": "NSD (m²)"},
            }
            | (params_dict.get("nsd_rename_display_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "nsd_chart": Node(
            async_task=draw_ecoplot.validate()
            .set_task_instance_id("nsd_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "group_by": "subject_name",
                "ecoplot_configs": [
                    {
                        "x_col": "Time",
                        "y_col": "NSD (m²)",
                        "plot_style": {"xperiodalignment": None},
                        "color_column": None,
                    }
                ],
                "tickformat": "%b-%Y",
                "widget_id": DependsOn("set_nsd_chart_title"),
            }
            | (params_dict.get("nsd_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("nsd_rename_display_columns"),
            },
        ),
        "nsd_chart_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("nsd_chart_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "v2",
            }
            | (params_dict.get("nsd_chart_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("nsd_chart"),
            },
        ),
        "nsd_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("nsd_chart_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("set_nsd_chart_title"),
            }
            | (params_dict.get("nsd_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("nsd_chart_html_url"),
            },
        ),
        "grouped_nsd_chart_widget_merge": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_nsd_chart_widget_merge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("nsd_chart_widget"),
            }
            | (params_dict.get("grouped_nsd_chart_widget_merge") or {}),
            method="call",
        ),
        "subject_tracking_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("subject_tracking_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": DependsOnSequence(
                    [
                        DependsOn("traj_grouped_map_widget"),
                        DependsOn("mean_speed_grouped_sv_widget"),
                        DependsOn("max_speed_grouped_sv_widget"),
                        DependsOn("num_location_grouped_sv_widget"),
                        DependsOn("nightday_ratio_grouped_sv_widget"),
                        DependsOn("total_dist_grouped_sv_widget"),
                        DependsOn("total_time_grouped_sv_widget"),
                        DependsOn("td_grouped_map_widget"),
                        DependsOn("traj_nightday_grouped_map_widget"),
                        DependsOn("grouped_nsd_chart_widget_merge"),
                    ],
                ),
                "groupers": DependsOn("groupers"),
                "time_range": DependsOn("time_range"),
                "warning": DependsOn("warn_if_mixed_subtype"),
            }
            | (params_dict.get("subject_tracking_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
