# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class SubjectGroup(BaseModel):
    subject_obs: SubjectObs | None = Field(None, title="")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: (
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
        | None
    ) = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: (
        list[
            BaseMaps
            | BaseMaps1
            | BaseMaps2
            | BaseMaps3
            | BaseMaps4
            | BaseMaps5
            | BaseMaps6
        ]
        | None
    ) = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class Percentile(str, Enum):
    field_50 = "50"
    field_60 = "60"
    field_70 = "70"
    field_80 = "80"
    field_90 = "90"
    field_95 = "95"
    field_99 = "99"
    field_99_999 = "99.999"
    field_100 = "100"


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(RootModel[str]):
    root: str = Field(..., title="Spatial Regions")


class TemporalGrouper(str, Enum):
    field_Y = "%Y"
    field_B = "%B"
    field_Y__m = "%Y-%m"
    field_j = "%j"
    field_d = "%d"
    field_A = "%A"
    field_H = "%H"
    field_Y__m__d = "%Y-%m-%d"


class ValueGrouper(str, Enum):
    subject_name = "subject_name"
    subject_subtype = "subject_subtype"
    subject_sex = "subject_sex"


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: confloat(ge=0.001) | None = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: confloat(gt=0.001) | None = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: confloat(ge=1.0) | None = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: confloat(gt=1.0) | None = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: confloat(gt=0.001) | None = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: confloat(gt=0.001) | None = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class AutoScaleOrCustom(str, Enum):
    Auto_scale = "Auto-scale"


class AutoScaleGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Auto-scale"] = Field(
        "Auto-scale", title="Grid Cell Size"
    )


class AutoScaleOrCustom1(str, Enum):
    Customize = "Customize"


class CustomGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Customize"] = Field(
        "Customize", title="Grid Cell Size"
    )
    grid_cell_size: confloat(lt=10000.0, gt=0.0) | None = Field(
        5000,
        description="Define the resolution of the raster grid (in the unit of measurement defined by the coordinate reference system set below). A smaller grid cell size provides more detail, while a larger size generalizes the data.",
        title="Custom Grid Cell Size",
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper | SpatialGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class SubjectTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: TrajectorySegmentFilter | None = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class SetEtdArgs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        0.7,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )
    auto_scale_or_custom_cell_size: (
        AutoScaleGridCellSize | CustomGridCellSize | None
    ) = Field(
        default_factory=lambda: AutoScaleGridCellSize.model_validate(
            {"auto_scale_or_custom": "Auto-scale"}
        ),
        title="Grid Cell Size",
    )
    crs: str | None = Field(
        "EPSG:3857",
        description="The coordinate reference system in which to perform the calculation, must be a valid CRS authority code, for example ESRI:53042",
        title="Coordinate Reference System",
    )
    max_speed_factor: float | None = Field(
        1.05,
        description="An estimate of the subject's maximum speed as a factor of the maximum measured speed value in the dataset.",
        title="Max Speed Factor (Kilometers per Hour)",
    )
    expansion_factor: float | None = Field(
        1.05,
        description="Controls how far time density values spread across the grid, affecting the smoothness of the output.",
        title="Shape Buffer Expansion Factor",
    )
    percentiles: list[Percentile] | None = Field(
        ["50", "60", "70", "80", "90", "99.999"],
        description="Choose the time density percentile bins to display.",
        min_length=1,
        title="Percentile Levels",
    )


class TimeDensityMap(BaseModel):
    set_etd_args: SetEtdArgs | None = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    er_client_name: ErClientName | None = Field(None, title="Data Source")
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    Subject_Group: SubjectGroup | None = Field(
        None, alias="Subject Group", description="Choose a subject group to analyze"
    )
    groupers: Groupers | None = Field(None, title="Group Data")
    subject_traj: SubjectTraj | None = Field(None, title="Trajectory Segment Filter")
    base_map_defs: BaseMapDefs | None = Field(None, title="Map Base Layers")
    Time_Density_Map: TimeDensityMap | None = Field(
        None,
        alias="Time Density Map",
        description="These settings show a grid-based heatmap showing where subjects spent the most time.",
    )
