# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from pydantic import BaseModel

from ecoscope_workflows_core.tasks.results import DashboardJson


class ResponseModel(BaseModel):
    result: DashboardJson | None = None
    error: str | None = None
    trace: str | None = None
