name: Tag

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get existing tags
      - name: List existing tags
        run: |
          git tag -l
      - name: Get workflow id from spec.yaml
        id: get_workflow_id
        uses: mikefarah/yq@v4
        with:
          cmd: yq -r '.id' spec.yaml
      - name: Transform workflow id to workflow directory name
        id: workflow_directory
        run: |
          export WORKFLOW_NAME=$(echo "${{ steps.get_workflow_id.outputs.result }}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
          echo "name=ecoscope-workflows-${WORKFLOW_NAME}-workflow" >> $GITHUB_OUTPUT
      - name: Create tag from VERSION.yaml
        id: create_tag
        uses: mikefarah/yq@v4
        with:
          cmd: yq -r '"v" + (.MAJ | tostring) + "." + (.MIN | tostring) + "." + (.PATCH | tostring)' ${{ steps.workflow_directory.outputs.name }}/VERSION.yaml
      - name: Tag
        run: |
          echo "Tagging version ${{ steps.create_tag.outputs.result }}"
          git tag ${{ steps.create_tag.outputs.result }}
          git tag -l
      - name: Push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin --tags
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ steps.create_tag.outputs.result }}'
          --repo '${{ github.repository }}'
          --generate-notes
